version: "2"

run:
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gocritic
    - bodyclose
    - dupl
    - goconst
    - gocyclo
    - gosec
    - unconvert
    - unparam
    - errorlint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
