// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMigrate is an autogenerated mock type for the Migrate type
type MockMigrate struct {
	mock.Mock
}

type MockMigrate_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMigrate) EXPECT() *MockMigrate_Expecter {
	return &MockMigrate_Expecter{mock: &_m.Mock}
}

// Migrate provides a mock function with given fields: ctx
func (_m *MockMigrate) Migrate(ctx context.Context) (int64, int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 int64
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) int64); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMigrate_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type MockMigrate_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMigrate_Expecter) Migrate(ctx interface{}) *MockMigrate_Migrate_Call {
	return &MockMigrate_Migrate_Call{Call: _e.mock.On("Migrate", ctx)}
}

func (_c *MockMigrate_Migrate_Call) Run(run func(ctx context.Context)) *MockMigrate_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMigrate_Migrate_Call) Return(oldVer int64, newVer int64, err error) *MockMigrate_Migrate_Call {
	_c.Call.Return(oldVer, newVer, err)
	return _c
}

func (_c *MockMigrate_Migrate_Call) RunAndReturn(run func(context.Context) (int64, int64, error)) *MockMigrate_Migrate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMigrate creates a new instance of MockMigrate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMigrate(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMigrate {
	mock := &MockMigrate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
