// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTransactional is an autogenerated mock type for the Transactional type
type MockTransactional struct {
	mock.Mock
}

type MockTransactional_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactional) EXPECT() *MockTransactional_Expecter {
	return &MockTransactional_Expecter{mock: &_m.Mock}
}

// InsideTx provides a mock function with given fields: ctx, fn
func (_m *MockTransactional) InsideTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for InsideTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactional_InsideTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsideTx'
type MockTransactional_InsideTx_Call struct {
	*mock.Call
}

// InsideTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *MockTransactional_Expecter) InsideTx(ctx interface{}, fn interface{}) *MockTransactional_InsideTx_Call {
	return &MockTransactional_InsideTx_Call{Call: _e.mock.On("InsideTx", ctx, fn)}
}

func (_c *MockTransactional_InsideTx_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *MockTransactional_InsideTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockTransactional_InsideTx_Call) Return(_a0 error) *MockTransactional_InsideTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactional_InsideTx_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *MockTransactional_InsideTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactional creates a new instance of MockTransactional. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactional(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactional {
	mock := &MockTransactional{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
